services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: "hoarder"
      POSTGRES_PASSWORD: "hoarder"
      POSTGRES_DB: "hoarder"
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
